CREATE TABLE IF NOT EXISTS analytics (
    id SERIAL PRIMARY KEY,
    url VARCHAR NOT NULL,
    access_time TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR NOT NULL,
    user_agent VARCHAR NOT NULL,
    referrer VARCHAR
);