services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: url_shortener_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data
      - ./database:/docker-entrypoint-initdb.d  # Initialization scripts
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # Persist Redis data

  url_shortening_service:
    build:
      context: ./url_shortening_service
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: app
      SQLALCHEMY_DATABASE_URI: postgresql://user:password@db:5432/url_shortener_db
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
  
  redirection_service:
    build:
      context: ./redirection_service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
