{
 "title": "LinkLoom",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{job=~\"analytics|api|qr-code-generator|url-shortener\"}) by (job, method, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (in seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\"analytics|api|qr-code-generator|url-shortener\"}[5m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average request duration (API)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{job=\"api\"}[5m]) / rate(flask_http_request_duration_seconds_count{job=\"api\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory allocation for the (QR Code Generator)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"qr-code-generator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of HTTP requests handled (URL Shortener)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "flask_http_request_total{job=\"url-shortener\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (in bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{job=~\"analytics|api|qr-code-generator|url-shortener\"}) by (job)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}