apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: qr-code-generator
  name: qr-code-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: qr-code-generator
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: qr-code-generator
    spec:
      containers:
        - image: docker.io/prajjwalyd/qr-code-generator
          name: qr-code-generator
          ports:
            - containerPort: 5002
              protocol: TCP
      restartPolicy: Always
