name: Build and Push

on:
  workflow_call:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push api image
        run: |
          docker build -t docker.io/prajjwalyd/api:latest ./api
          docker push docker.io/prajjwalyd/api:latest

      - name: Build and push url-shortener image
        run: |
          docker build -t docker.io/prajjwalyd/url-shortener:latest ./url-shortener
          docker push docker.io/prajjwalyd/url-shortener:latest

      - name: Build and push qr-code-generator image
        run: |
          docker build -t docker.io/prajjwalyd/qr-code-generator:latest ./qr-code-generator
          docker push docker.io/prajjwalyd/qr-code-generator:latest

      - name: Build and push analytics image
        run: |
          docker build -t docker.io/prajjwalyd/analytics:latest ./analytics
          docker push docker.io/prajjwalyd/analytics:latest
