name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  test:
    needs: setup
    uses: ./.github/workflows/test.yml

  build_and_push:
    needs: test
    uses: ./.github/workflows/build_and_push.yml
    secrets: inherit
